name: UI Tests
on:
  push:
    branches: [master]
  pull_request:

jobs:
  run-ui-test:
    name: run tests for ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            runIde: |
              export DISPLAY=:99.0
              Xvfb -ac :99 -screen 0 1920x1080x24 &
              sleep 10
              mkdir -p build/reports
              ./gradlew runIdeForUiTests > build/reports/idea.log &
            runTests: |
              export DISPLAY=:99.0
              ./gradlew uiTest
            url: http://127.0.0.1:8082
            reportName: ui-test-fails-report-linux

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4.1.5

      - name: Setup Java
        uses: actions/setup-java@v4.5.0
        with:
          distribution: zulu
          java-version: 17

      - name: Clean
        run: ./gradlew clean

      - name: Run Idea
        run: ${{ matrix.runIde }}

      - name: Wait for Idea started
        uses: jtalk/url-health-check-action@v3
        with:
          url: ${{ matrix.url }}
          max-attempts: 15
          retry-delay: 30s

      - name: Run tests
        run: ${{ matrix.runTests }}

      - name: Copy logs
        if: ${{ failure() }}
        run: mv build/idea-sandbox/system/log/ build/reports

      - name: Save fails report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.reportName }}
          path: |
            build/reports
